# Generated by Django 4.2 on 2023-04-07 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DeviceManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceinstance',
            old_name='id',
            new_name='DeviceID',
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='accessedUsers',
            field=models.ManyToManyField(related_name='accessedGroup', to=settings.AUTH_USER_MODEL),
        ),
    ]
